In [ ]:
#Se instala las librerías necesarias
%pip install selenium pandas openpyxl webdriver-manager

Requirement already satisfied: selenium in c:\users\asus\anaconda3\lib\site-packages (4.41.0)
Requirement already satisfied: pandas in c:\users\asus\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\asus\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: webdriver-manager in c:\users\asus\anaconda3\lib\site-packages (4.0.2)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (2026.1.4)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\asus\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\asus\anaconda3\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\asus\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\asus\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: requests in c:\users\asus\anaconda3\lib\site-packages (from webdriver-manager) (2.32.5)
Requirement already satisfied: python-dotenv in c:\users\asus\anaconda3\lib\site-packages (from webdriver-manager) (1.1.0)
Requirement already satisfied: packaging in c:\users\asus\anaconda3\lib\site-packages (from webdriver-manager) (25.0)
Requirement already satisfied: pycparser in c:\users\asus\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\asus\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.4.4)

## ⚙️ Step 1 — Install Dependencies

We install the four required libraries. Using `%pip` (instead of `!pip`) ensures the packages are installed in the same Python environment that the notebook kernel is using.

# 🎓 Task 1 — Web Scraping: UNMSM Admissions 2026-II

This notebook automates the extraction of applicant results from the official UNMSM (Universidad Nacional Mayor de San Marcos) admissions website for the **2026-II cycle**.

Using **Selenium**, the scraper navigates the site, collects all 111 academic programs, paginates through every result page, and consolidates everything into a single Excel file with **25,880 total records**.

**Target:** `https://admision.unmsm.edu.pe/Website20262/A/A.html`

---

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# 1. Se configura  el servicio para que descargue el driver automáticamente
service = Service(ChromeDriverManager().install())

# 2. Se inicia el navegador (Chrome)
driver = webdriver.Chrome(service=service)

# 3. Se maximiza la ventana para que Selenium "vea" todos los elementos
driver.maximize_window()

## 🌐 Step 2 — Launch the Browser

We use `webdriver-manager` to automatically download the correct version of ChromeDriver — no manual setup needed. The browser window is maximized so Selenium can detect all elements correctly, even those that only render at full screen width.

In [3]:
# 1. Se importa lo necesario para las esperas
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# 2. Se define la URL de inicio (Asegúrate de que el driver esté abierto)
url_principal = "https://admision.unmsm.edu.pe/Website20262/A/A.html"
driver.get(url_principal)

# 3. Espera explícita: Aguardamos a que la tabla cargue en el DOM
wait = WebDriverWait(driver, 20)
# Se usa el selector que refleja la jerarquía que se encontró:
# table.table-striped busca la tabla, y el espacio + 'a' busca los links dentro
selector_carreras = "table.table-striped tbody tr td a"
enlaces_carreras = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, selector_carreras)))

# 4. Se guarda la información en una lista de diccionarios
lista_carreras = []
for e in enlaces_carreras:
    lista_carreras.append({
        "carrera": e.text.strip(),
        "url": e.get_attribute("href")  # Esto extrae el link del atributo href
    })

# 5. Se muestra la cantidad de carreras encontradas
print(f"Se han detectado {len(lista_carreras)} carreras.")

# 6. Le echamos un ojito al diccionario que contiene a las carreras con sus respectivo URL
lista_carreras

# Con este código se puede comprobar si la extracción fue correcta
# var_name= [c for c in lista_carreras if "Aquí pon el nombre de la carrera" in c['carrera']]
#print(f"La carrera {var_name}" fue encontrada.)

Se han detectado 111 carreras.

[{'carrera': 'ADMINISTRACIÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/091/results.html'},
 {'carrera': 'ADMINISTRACIÓN - CHILCA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0914/results.html'},
 {'carrera': 'ADMINISTRACIÓN - HUARAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0912/results.html'},
 {'carrera': 'ADMINISTRACIÓN - S.J.L',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0911/results.html'},
 {'carrera': 'ADMINISTRACIÓN - VILLA RICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0915/results.html'},
 {'carrera': 'ADMINISTRACIÓN DE LA GASTRONOMÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/094/results.html'},
 {'carrera': 'ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/093/results.html'},
 {'carrera': 'ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES - HUARAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0932/results.html'},
 {'carrera': 'ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES - S.J.L',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0931/results.html'},
 {'carrera': 'ADMINISTRACIÓN DE TURISMO',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/092/results.html'},
 {'carrera': 'ADMINISTRACIÓN DE TURISMO - S.J.L',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0921/results.html'},
 {'carrera': 'ADMINISTRACIÓN MARÍTIMA Y PORTUARIA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/095/results.html'},
 {'carrera': 'ADMINISTRACION MARITIMA Y PORTUARIA - CHANCAY',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0957/results.html'},
 {'carrera': 'ANTROPOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/153/results.html'},
 {'carrera': 'ARQUEOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/154/results.html'},
 {'carrera': 'ARQUITECTURA Y URBANISMO',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/169/results.html'},
 {'carrera': 'ARTE',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/036/results.html'},
 {'carrera': 'AUDITORÍA EMPRESARIAL Y DEL SECTOR PÚBLICO',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/113/results.html'},
 {'carrera': 'AUDITORÍA EMPRESARIAL Y DEL SECTOR PÚBLICO - S.J.L',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1131/results.html'},
 {'carrera': 'BIBLIOTECOLOGÍA Y CIENCIAS DE LA INFORMACIÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/037/results.html'},
 {'carrera': 'CIENCIA DE LA COMPUTACIÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/203/results.html'},
 {'carrera': 'CIENCIA POLÍTICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/023/results.html'},
 {'carrera': 'CIENCIAS BIOLÓGICAS',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/101/results.html'},
 {'carrera': 'CIENCIAS DE LOS ALIMENTOS',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/042/results.html'},
 {'carrera': 'COMPUTACIÓN CIENTÍFICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/145/results.html'},
 {'carrera': 'COMUNICACIÓN SOCIAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/035/results.html'},
 {'carrera': 'CONSERVACIÓN Y RESTAURACIÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/039/results.html'},
 {'carrera': 'CONTABILIDAD',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/111/results.html'},
 {'carrera': 'CONTABILIDAD - CHILCA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1114/results.html'},
 {'carrera': 'CONTABILIDAD - HUARAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1112/results.html'},
 {'carrera': 'CONTABILIDAD - OYÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1113/results.html'},
 {'carrera': 'CONTABILIDAD - S.J.L',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1111/results.html'},
 {'carrera': 'CONTABILIDAD - VILLA RICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1115/results.html'},
 {'carrera': 'CRIMINALÍSTICA FINANCIERA FORENSE',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/115/results.html'},
 {'carrera': 'DANZA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/038/results.html'},
 {'carrera': 'DERECHO',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/022/results.html'},
 {'carrera': 'DERECHO - CHILCA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0224/results.html'},
 {'carrera': 'DERECHO - VILLA RICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0225/results.html'},
 {'carrera': 'ECONOMÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/121/results.html'},
 {'carrera': 'ECONOMÍA INTERNACIONAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/123/results.html'},
 {'carrera': 'ECONOMÍA PÚBLICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/122/results.html'},
 {'carrera': 'EDUCACIÓN FÍSICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/062/results.html'},
 {'carrera': 'EDUCACIÓN FÍSICA - OYÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0623/results.html'},
 {'carrera': 'EDUCACIÓN INICIAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0611/results.html'},
 {'carrera': 'EDUCACIÓN PRIMARIA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0612/results.html'},
 {'carrera': 'EDUCACIÓN SECUNDARIA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0613/results.html'},
 {'carrera': 'ENFERMERÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/013/results.html'},
 {'carrera': 'ESTADÍSTICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/142/results.html'},
 {'carrera': 'FARMACIA Y BIOQUÍMICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/041/results.html'},
 {'carrera': 'FILOSOFÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/033/results.html'},
 {'carrera': 'FÍSICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/131/results.html'},
 {'carrera': 'GENÉTICA Y BIOTECNOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/102/results.html'},
 {'carrera': 'GEOFÍSICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/133/results.html'},
 {'carrera': 'GEOGRAFÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/157/results.html'},
 {'carrera': 'GESTIÓN TRIBUTARIA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/112/results.html'},
 {'carrera': 'GESTIÓN TRIBUTARIA - S.J.L',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1121/results.html'},
 {'carrera': 'HISTORIA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/151/results.html'},
 {'carrera': 'INGENIERÍA AGROINDUSTRIAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/073/results.html'},
 {'carrera': 'INGENIERÍA AMBIENTAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/168/results.html'},
 {'carrera': 'INGENIERÍA BIOMÉDICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/194/results.html'},
 {'carrera': 'INGENIERÍA CIVIL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/167/results.html'},
 {'carrera': 'INGENIERÍA DE INTELIGENCIA ARTIFICIAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/204/results.html'},
 {'carrera': 'INGENIERÍA DE MINAS',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/165/results.html'},
 {'carrera': 'INGENIERÍA DE MINAS - OYÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1653/results.html'},
 {'carrera': 'INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/173/results.html'},
 {'carrera': 'INGENIERÍA DE SISTEMAS',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/201/results.html'},
 {'carrera': 'INGENIERÍA DE SOFTWARE',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/202/results.html'},
 {'carrera': 'INGENIERÍA DE TELECOMUNICACIONES',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/193/results.html'},
 {'carrera': 'INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/175/results.html'},
 {'carrera': 'INGENIERIA DEL AGUA Y TECNOLOGIAS DE TRATAMIENTO',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/074/results.html'},
 {'carrera': 'INGENIERÍA ELÉCTRICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/192/results.html'},
 {'carrera': 'INGENIERÍA ELÉCTRICA - CHILCA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1924/results.html'},
 {'carrera': 'INGENIERÍA ELECTRÓNICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/191/results.html'},
 {'carrera': 'INGENIERÍA GEOGRÁFICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/163/results.html'},
 {'carrera': 'INGENIERÍA GEOLÓGICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/162/results.html'},
 {'carrera': 'INGENIERÍA GEOLÓGICA - OYÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1623/results.html'},
 {'carrera': 'INGENIERÍA INDUSTRIAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/171/results.html'},
 {'carrera': 'INGENIERÍA INDUSTRIAL - CHILCA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1714/results.html'},
 {'carrera': 'INGENIERÍA LOGÍSTICA Y CADENA DE SUMISTRO DIGITAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/174/results.html'},
 {'carrera': 'INGENIERÍA MECÁNICA DE FLUIDOS',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/132/results.html'},
 {'carrera': 'INGENIERÍA MECATRONICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/195/results.html'},
 {'carrera': 'INGENIERÍA METALÚRGICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/166/results.html'},
 {'carrera': 'INGENIERÍA NUCLEAR',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/196/results.html'},
 {'carrera': 'INGENIERÍA QUÍMICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/072/results.html'},
 {'carrera': 'INGENIERÍA TEXTIL Y CONFECCIONES',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/172/results.html'},
 {'carrera': 'INVESTIGACIÓN OPERATIVA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/144/results.html'},
 {'carrera': 'INVESTIGACIÓN OPERATIVA - CHILCA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1444/results.html'},
 {'carrera': 'LENGUAS, TRADUCCIÓN E INTERPRETACIÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0310/results.html'},
 {'carrera': 'LINGUÍSTICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/034/results.html'},
 {'carrera': 'LITERATURA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/031/results.html'},
 {'carrera': 'MARKETING',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/096/results.html'},
 {'carrera': 'MATEMÁTICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/141/results.html'},
 {'carrera': 'MEDICINA HUMANA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/011/results.html'},
 {'carrera': 'MEDICINA VETERINARIA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/081/results.html'},
 {'carrera': 'MICROBIOLOGÍA Y PARASITOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/103/results.html'},
 {'carrera': 'NUTRICION',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/015/results.html'},
 {'carrera': 'OBSTETRICIA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/012/results.html'},
 {'carrera': 'ODONTOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/051/results.html'},
 {'carrera': 'PRESUPUESTO Y FINANZAS PÚBLICAS',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/114/results.html'},
 {'carrera': 'PRESUPUESTO Y FINANZAS PÚBLICAS - S.J.L',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1141/results.html'},
 {'carrera': 'PSICOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/181/results.html'},
 {'carrera': 'PSICOLOGÍA - CHILCA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/1814/results.html'},
 {'carrera': 'PSICOLOGÍA ORGANIZACIONAL Y DE LA GESTIÓN HUMANA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/182/results.html'},
 {'carrera': 'QUÍMICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/071/results.html'},
 {'carrera': 'SOCIOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/152/results.html'},
 {'carrera': 'TEC. MED. LAB. CLÍNICO Y ANATOMÍA PATOLÓGICA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0141/results.html'},
 {'carrera': 'TEC. MED. RADIOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0143/results.html'},
 {'carrera': 'TEC. MED. TERAPIA FÍSICA Y REHABILITACIÓN',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0142/results.html'},
 {'carrera': 'TEC. MED. TERAPIA OCUPACIONAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/0144/results.html'},
 {'carrera': 'TOXICOLOGÍA',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/043/results.html'},
 {'carrera': 'TRABAJO SOCIAL',
  'url': 'https://admision.unmsm.edu.pe/Website20262/A/155/results.html'}]

## 🗂️ Step 3 — Collect All Program URLs

We navigate to the main admissions page and extract the name and URL of every academic program listed in the results table. An explicit wait (`WebDriverWait`) ensures we only proceed once the table has fully loaded in the DOM — this avoids empty results caused by slow page rendering.

> **Result:** 111 academic programs detected across all faculties of UNMSM.

In [4]:
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC

def extraer_postulantes_carrera(driver, url_carrera, nombre_carrera):
    """
    Navega por la carrera, cambia a 100 registros y usa el botón 'Siguiente'
    hasta que se deshabilite, capturando datos de atributos data-score/merit.
    """
    driver.get(url_carrera)
    wait = WebDriverWait(driver, 25) # Espera robusta para San Marcos
    
    # 1. Intentar poner la visualización en 100 registros (ID: dt-length-0)
    try:
        select_element = wait.until(EC.element_to_be_clickable((By.ID, "dt-length-0")))
        select = Select(select_element)
        select.select_by_value("100")
        time.sleep(5) # Tiempo para que DataTables procese el cambio
    except:
        print(f"No se pudo cambiar a 100 registros en {nombre_carrera}")

    resultados_carrera = []
    
    while True:
        # 2. Esperar a que la tabla de la HOJA ACTUAL cargue
        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#tablaPostulantes tbody tr")))
        filas = driver.find_elements(By.CSS_SELECTOR, "#tablaPostulantes tbody tr")
        
        # 3. Extraer datos de la hoja en la que estamos
        for fila in filas:
            columnas = fila.find_elements(By.TAG_NAME, "td")
            if len(columnas) >= 6:
                # SOLUCIÓN DATOS VACÍOS: Extraemos de los atributos del HTML
                puntaje = columnas[3].get_attribute("data-score")
                merito = columnas[4].get_attribute("data-merit")
                
                resultados_carrera.append({
                    "Carrera": nombre_carrera,
                    "Código": columnas[0].text.strip(),
                    "Apellidos y Nombres": columnas[1].text.strip(),
                    "Escuela": columnas[2].text.strip(),
                    "Puntaje": puntaje if puntaje else "0.000",
                    "Mérito E.P.": merito if merito else "",
                    "Observación": columnas[5].text.strip()
                })

        # 4. LÓGICA DE MOVIMIENTO: Clic en 'Siguiente' (Paginación)
        try:
            # Identificamos el li que envuelve al botón Siguiente
            # El selector li.dt-paging-button:has(button.next) es el más preciso para tu HTML
            li_siguiente = driver.find_element(By.CSS_SELECTOR, "li.dt-paging-button:has(button.next)")
            
            # Si el contenedor li tiene la clase 'disabled', paramos el bucle
            if "disabled" in li_siguiente.get_attribute("class"):
                print(f"Fin de {nombre_carrera} alcanzado. Registros: {len(resultados_carrera)}")
                break
            
            # Si no está disabled, buscamos el botón interno y clickeamos con JS
            boton_next = li_siguiente.find_element(By.CSS_SELECTOR, "button.next")
            driver.execute_script("arguments[0].click();", boton_next)
            
            # ESPERA CRUCIAL: Pausa para que el contenido de la tabla cambie realmente
            time.sleep(4) 
            
        except Exception as e:
            print(f"Terminando paginación por seguridad en {nombre_carrera}")
            break
            
    return resultados_carrera

## 🔧 Step 4 — Define the Scraping Function

We define a reusable function `extraer_postulantes_carrera()` that handles one academic program at a time. It navigates to the program's results page, switches the table display to 100 rows per page, and iterates through every page using the "Next" button until it is disabled.

Key design decisions:
- **`data-score` and `data-merit` attributes** — the score and merit values are embedded in HTML attributes, not visible text. Direct `element.text` would return empty strings, so we use `get_attribute()` instead.
- **JavaScript click** — the pagination button is clicked via `execute_script()` to bypass potential overlay issues that block standard Selenium clicks.
- **`time.sleep(4)`** — a deliberate pause after each page turn gives DataTables time to re-render the new rows before we read them.

In [5]:
import os

# 1. Aseguramos que la lista 'todos_los_datos' empiece limpia
todos_los_datos = []

# 2. BUCLE MAESTRO: Iteramos por TODAS las carreras de 'lista_carreras'
# (Eliminamos el [:2] para que recorra la lista completa)
for i, carrera_info in enumerate(lista_carreras):
    print(f"[{i+1}/{len(lista_carreras)}] Procesando: {carrera_info['carrera']}")
    
    try:
        # Llamamos a tu función corregida
        datos = extraer_postulantes_carrera(driver, carrera_info['url'], carrera_info['carrera'])
        
        # Consolidamos los datos encontrados
        todos_los_datos.extend(datos)
        print(f"Éxito: {len(datos)} registros capturados.")
        
    except Exception as e:
        print(f"Error en {carrera_info['carrera']}: {e}")
        # Si falla una, continuamos con la siguiente para no perder el progreso
        continue

# 3. CONSOLIDACIÓN FINAL EN PANDAS
if todos_los_datos:
    df_final = pd.DataFrame(todos_los_datos)
    
    # 4. EXPORTACIÓN A EXCEL (Carpeta output/)
    output_path = "output/resultados_sanmarcos.xlsx"
    
    # Usamos index=False para que no cree la columna de números a la izquierda
    df_final.to_excel(output_path, index=False)
    
    print("-" * 30)
    print(f"¡PROCESO COMPLETADO!")
    print(f"Total de registros consolidados: {len(df_final)}")
    print(f"Archivo guardado en: {output_path}")
else:
    print("No se recolectó ninguna información. Revisa el driver.")

# 5. Cerramos el navegador al terminar todo
driver.quit()

[1/111] Procesando: ADMINISTRACIÓN
Fin de ADMINISTRACIÓN alcanzado. Registros: 553
Éxito: 553 registros capturados.
[2/111] Procesando: ADMINISTRACIÓN - CHILCA
Fin de ADMINISTRACIÓN - CHILCA alcanzado. Registros: 33
Éxito: 33 registros capturados.
[3/111] Procesando: ADMINISTRACIÓN - HUARAL
Fin de ADMINISTRACIÓN - HUARAL alcanzado. Registros: 31
Éxito: 31 registros capturados.
[4/111] Procesando: ADMINISTRACIÓN - S.J.L
Fin de ADMINISTRACIÓN - S.J.L alcanzado. Registros: 44
Éxito: 44 registros capturados.
[5/111] Procesando: ADMINISTRACIÓN - VILLA RICA
Fin de ADMINISTRACIÓN - VILLA RICA alcanzado. Registros: 33
Éxito: 33 registros capturados.
[6/111] Procesando: ADMINISTRACIÓN DE LA GASTRONOMÍA
Fin de ADMINISTRACIÓN DE LA GASTRONOMÍA alcanzado. Registros: 127
Éxito: 127 registros capturados.
[7/111] Procesando: ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES
Fin de ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES alcanzado. Registros: 805
Éxito: 805 registros capturados.
[8/111] Procesando: ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES - HUARAL
Fin de ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES - HUARAL alcanzado. Registros: 36
Éxito: 36 registros capturados.
[9/111] Procesando: ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES - S.J.L
Fin de ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES - S.J.L alcanzado. Registros: 75
Éxito: 75 registros capturados.
[10/111] Procesando: ADMINISTRACIÓN DE TURISMO
Fin de ADMINISTRACIÓN DE TURISMO alcanzado. Registros: 172
Éxito: 172 registros capturados.
[11/111] Procesando: ADMINISTRACIÓN DE TURISMO - S.J.L
Fin de ADMINISTRACIÓN DE TURISMO - S.J.L alcanzado. Registros: 25
Éxito: 25 registros capturados.
[12/111] Procesando: ADMINISTRACIÓN MARÍTIMA Y PORTUARIA
Fin de ADMINISTRACIÓN MARÍTIMA Y PORTUARIA alcanzado. Registros: 140
Éxito: 140 registros capturados.
[13/111] Procesando: ADMINISTRACION MARITIMA Y PORTUARIA - CHANCAY
Fin de ADMINISTRACION MARITIMA Y PORTUARIA - CHANCAY alcanzado. Registros: 21
Éxito: 21 registros capturados.
[14/111] Procesando: ANTROPOLOGÍA
Fin de ANTROPOLOGÍA alcanzado. Registros: 57
Éxito: 57 registros capturados.
[15/111] Procesando: ARQUEOLOGÍA
Fin de ARQUEOLOGÍA alcanzado. Registros: 73
Éxito: 73 registros capturados.
[16/111] Procesando: ARQUITECTURA Y URBANISMO
Fin de ARQUITECTURA Y URBANISMO alcanzado. Registros: 514
Éxito: 514 registros capturados.
[17/111] Procesando: ARTE
Fin de ARTE alcanzado. Registros: 52
Éxito: 52 registros capturados.
[18/111] Procesando: AUDITORÍA EMPRESARIAL Y DEL SECTOR PÚBLICO
Fin de AUDITORÍA EMPRESARIAL Y DEL SECTOR PÚBLICO alcanzado. Registros: 121
Éxito: 121 registros capturados.
[19/111] Procesando: AUDITORÍA EMPRESARIAL Y DEL SECTOR PÚBLICO - S.J.L
Fin de AUDITORÍA EMPRESARIAL Y DEL SECTOR PÚBLICO - S.J.L alcanzado. Registros: 47
Éxito: 47 registros capturados.
[20/111] Procesando: BIBLIOTECOLOGÍA Y CIENCIAS DE LA INFORMACIÓN
Fin de BIBLIOTECOLOGÍA Y CIENCIAS DE LA INFORMACIÓN alcanzado. Registros: 83
Éxito: 83 registros capturados.
[21/111] Procesando: CIENCIA DE LA COMPUTACIÓN
Fin de CIENCIA DE LA COMPUTACIÓN alcanzado. Registros: 134
Éxito: 134 registros capturados.
[22/111] Procesando: CIENCIA POLÍTICA
Fin de CIENCIA POLÍTICA alcanzado. Registros: 372
Éxito: 372 registros capturados.
[23/111] Procesando: CIENCIAS BIOLÓGICAS
Fin de CIENCIAS BIOLÓGICAS alcanzado. Registros: 187
Éxito: 187 registros capturados.
[24/111] Procesando: CIENCIAS DE LOS ALIMENTOS
Fin de CIENCIAS DE LOS ALIMENTOS alcanzado. Registros: 41
Éxito: 41 registros capturados.
[25/111] Procesando: COMPUTACIÓN CIENTÍFICA
Fin de COMPUTACIÓN CIENTÍFICA alcanzado. Registros: 42
Éxito: 42 registros capturados.
[26/111] Procesando: COMUNICACIÓN SOCIAL
Fin de COMUNICACIÓN SOCIAL alcanzado. Registros: 301
Éxito: 301 registros capturados.
[27/111] Procesando: CONSERVACIÓN Y RESTAURACIÓN
Fin de CONSERVACIÓN Y RESTAURACIÓN alcanzado. Registros: 39
Éxito: 39 registros capturados.
[28/111] Procesando: CONTABILIDAD
Fin de CONTABILIDAD alcanzado. Registros: 479
Éxito: 479 registros capturados.
[29/111] Procesando: CONTABILIDAD - CHILCA
Fin de CONTABILIDAD - CHILCA alcanzado. Registros: 46
Éxito: 46 registros capturados.
[30/111] Procesando: CONTABILIDAD - HUARAL
Fin de CONTABILIDAD - HUARAL alcanzado. Registros: 20
Éxito: 20 registros capturados.
[31/111] Procesando: CONTABILIDAD - OYÓN
Fin de CONTABILIDAD - OYÓN alcanzado. Registros: 21
Éxito: 21 registros capturados.
[32/111] Procesando: CONTABILIDAD - S.J.L
Fin de CONTABILIDAD - S.J.L alcanzado. Registros: 61
Éxito: 61 registros capturados.
[33/111] Procesando: CONTABILIDAD - VILLA RICA
Fin de CONTABILIDAD - VILLA RICA alcanzado. Registros: 19
Éxito: 19 registros capturados.
[34/111] Procesando: CRIMINALÍSTICA FINANCIERA FORENSE
Fin de CRIMINALÍSTICA FINANCIERA FORENSE alcanzado. Registros: 168
Éxito: 168 registros capturados.
[35/111] Procesando: DANZA
Fin de DANZA alcanzado. Registros: 6
Éxito: 6 registros capturados.
[36/111] Procesando: DERECHO
Fin de DERECHO alcanzado. Registros: 1873
Éxito: 1873 registros capturados.
[37/111] Procesando: DERECHO - CHILCA
Fin de DERECHO - CHILCA alcanzado. Registros: 59
Éxito: 59 registros capturados.
[38/111] Procesando: DERECHO - VILLA RICA
Fin de DERECHO - VILLA RICA alcanzado. Registros: 51
Éxito: 51 registros capturados.
[39/111] Procesando: ECONOMÍA
Fin de ECONOMÍA alcanzado. Registros: 659
Éxito: 659 registros capturados.
[40/111] Procesando: ECONOMÍA INTERNACIONAL
Fin de ECONOMÍA INTERNACIONAL alcanzado. Registros: 311
Éxito: 311 registros capturados.
[41/111] Procesando: ECONOMÍA PÚBLICA
Fin de ECONOMÍA PÚBLICA alcanzado. Registros: 174
Éxito: 174 registros capturados.
[42/111] Procesando: EDUCACIÓN FÍSICA
Fin de EDUCACIÓN FÍSICA alcanzado. Registros: 160
Éxito: 160 registros capturados.
[43/111] Procesando: EDUCACIÓN FÍSICA - OYÓN
Fin de EDUCACIÓN FÍSICA - OYÓN alcanzado. Registros: 20
Éxito: 20 registros capturados.
[44/111] Procesando: EDUCACIÓN INICIAL
Fin de EDUCACIÓN INICIAL alcanzado. Registros: 179
Éxito: 179 registros capturados.
[45/111] Procesando: EDUCACIÓN PRIMARIA
Fin de EDUCACIÓN PRIMARIA alcanzado. Registros: 146
Éxito: 146 registros capturados.
[46/111] Procesando: EDUCACIÓN SECUNDARIA
Fin de EDUCACIÓN SECUNDARIA alcanzado. Registros: 361
Éxito: 361 registros capturados.
[47/111] Procesando: ENFERMERÍA
Fin de ENFERMERÍA alcanzado. Registros: 602
Éxito: 602 registros capturados.
[48/111] Procesando: ESTADÍSTICA
Fin de ESTADÍSTICA alcanzado. Registros: 65
Éxito: 65 registros capturados.
[49/111] Procesando: FARMACIA Y BIOQUÍMICA
Fin de FARMACIA Y BIOQUÍMICA alcanzado. Registros: 249
Éxito: 249 registros capturados.
[50/111] Procesando: FILOSOFÍA
Fin de FILOSOFÍA alcanzado. Registros: 38
Éxito: 38 registros capturados.
[51/111] Procesando: FÍSICA
Fin de FÍSICA alcanzado. Registros: 55
Éxito: 55 registros capturados.
[52/111] Procesando: GENÉTICA Y BIOTECNOLOGÍA
Fin de GENÉTICA Y BIOTECNOLOGÍA alcanzado. Registros: 170
Éxito: 170 registros capturados.
[53/111] Procesando: GEOFÍSICA
Fin de GEOFÍSICA alcanzado. Registros: 88
Éxito: 88 registros capturados.
[54/111] Procesando: GEOGRAFÍA
Fin de GEOGRAFÍA alcanzado. Registros: 58
Éxito: 58 registros capturados.
[55/111] Procesando: GESTIÓN TRIBUTARIA
Fin de GESTIÓN TRIBUTARIA alcanzado. Registros: 109
Éxito: 109 registros capturados.
[56/111] Procesando: GESTIÓN TRIBUTARIA - S.J.L
Fin de GESTIÓN TRIBUTARIA - S.J.L alcanzado. Registros: 45
Éxito: 45 registros capturados.
[57/111] Procesando: HISTORIA
Fin de HISTORIA alcanzado. Registros: 80
Éxito: 80 registros capturados.
[58/111] Procesando: INGENIERÍA AGROINDUSTRIAL
Fin de INGENIERÍA AGROINDUSTRIAL alcanzado. Registros: 136
Éxito: 136 registros capturados.
[59/111] Procesando: INGENIERÍA AMBIENTAL
Fin de INGENIERÍA AMBIENTAL alcanzado. Registros: 165
Éxito: 165 registros capturados.
[60/111] Procesando: INGENIERÍA BIOMÉDICA
Fin de INGENIERÍA BIOMÉDICA alcanzado. Registros: 239
Éxito: 239 registros capturados.
[61/111] Procesando: INGENIERÍA CIVIL
Fin de INGENIERÍA CIVIL alcanzado. Registros: 642
Éxito: 642 registros capturados.
[62/111] Procesando: INGENIERÍA DE INTELIGENCIA ARTIFICIAL
Fin de INGENIERÍA DE INTELIGENCIA ARTIFICIAL alcanzado. Registros: 512
Éxito: 512 registros capturados.
[63/111] Procesando: INGENIERÍA DE MINAS
Fin de INGENIERÍA DE MINAS alcanzado. Registros: 275
Éxito: 275 registros capturados.
[64/111] Procesando: INGENIERÍA DE MINAS - OYÓN
Fin de INGENIERÍA DE MINAS - OYÓN alcanzado. Registros: 41
Éxito: 41 registros capturados.
[65/111] Procesando: INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO
Fin de INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO alcanzado. Registros: 79
Éxito: 79 registros capturados.
[66/111] Procesando: INGENIERÍA DE SISTEMAS
Fin de INGENIERÍA DE SISTEMAS alcanzado. Registros: 875
Éxito: 875 registros capturados.
[67/111] Procesando: INGENIERÍA DE SOFTWARE
Fin de INGENIERÍA DE SOFTWARE alcanzado. Registros: 411
Éxito: 411 registros capturados.
[68/111] Procesando: INGENIERÍA DE TELECOMUNICACIONES
Fin de INGENIERÍA DE TELECOMUNICACIONES alcanzado. Registros: 125
Éxito: 125 registros capturados.
[69/111] Procesando: INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS
Fin de INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS alcanzado. Registros: 172
Éxito: 172 registros capturados.
[70/111] Procesando: INGENIERIA DEL AGUA Y TECNOLOGIAS DE TRATAMIENTO
Fin de INGENIERIA DEL AGUA Y TECNOLOGIAS DE TRATAMIENTO alcanzado. Registros: 57
Éxito: 57 registros capturados.
[71/111] Procesando: INGENIERÍA ELÉCTRICA
Fin de INGENIERÍA ELÉCTRICA alcanzado. Registros: 172
Éxito: 172 registros capturados.
[72/111] Procesando: INGENIERÍA ELÉCTRICA - CHILCA
Fin de INGENIERÍA ELÉCTRICA - CHILCA alcanzado. Registros: 18
Éxito: 18 registros capturados.
[73/111] Procesando: INGENIERÍA ELECTRÓNICA
Fin de INGENIERÍA ELECTRÓNICA alcanzado. Registros: 255
Éxito: 255 registros capturados.
[74/111] Procesando: INGENIERÍA GEOGRÁFICA
Fin de INGENIERÍA GEOGRÁFICA alcanzado. Registros: 89
Éxito: 89 registros capturados.
[75/111] Procesando: INGENIERÍA GEOLÓGICA
Fin de INGENIERÍA GEOLÓGICA alcanzado. Registros: 165
Éxito: 165 registros capturados.
[76/111] Procesando: INGENIERÍA GEOLÓGICA - OYÓN
Fin de INGENIERÍA GEOLÓGICA - OYÓN alcanzado. Registros: 23
Éxito: 23 registros capturados.
[77/111] Procesando: INGENIERÍA INDUSTRIAL
Fin de INGENIERÍA INDUSTRIAL alcanzado. Registros: 866
Éxito: 866 registros capturados.
[78/111] Procesando: INGENIERÍA INDUSTRIAL - CHILCA
Fin de INGENIERÍA INDUSTRIAL - CHILCA alcanzado. Registros: 40
Éxito: 40 registros capturados.
[79/111] Procesando: INGENIERÍA LOGÍSTICA Y CADENA DE SUMISTRO DIGITAL
Fin de INGENIERÍA LOGÍSTICA Y CADENA DE SUMISTRO DIGITAL alcanzado. Registros: 165
Éxito: 165 registros capturados.
[80/111] Procesando: INGENIERÍA MECÁNICA DE FLUIDOS
Fin de INGENIERÍA MECÁNICA DE FLUIDOS alcanzado. Registros: 87
Éxito: 87 registros capturados.
[81/111] Procesando: INGENIERÍA MECATRONICA
Fin de INGENIERÍA MECATRONICA alcanzado. Registros: 291
Éxito: 291 registros capturados.
[82/111] Procesando: INGENIERÍA METALÚRGICA
Fin de INGENIERÍA METALÚRGICA alcanzado. Registros: 73
Éxito: 73 registros capturados.
[83/111] Procesando: INGENIERÍA NUCLEAR
Fin de INGENIERÍA NUCLEAR alcanzado. Registros: 54
Éxito: 54 registros capturados.
[84/111] Procesando: INGENIERÍA QUÍMICA
Fin de INGENIERÍA QUÍMICA alcanzado. Registros: 173
Éxito: 173 registros capturados.
[85/111] Procesando: INGENIERÍA TEXTIL Y CONFECCIONES
Fin de INGENIERÍA TEXTIL Y CONFECCIONES alcanzado. Registros: 102
Éxito: 102 registros capturados.
[86/111] Procesando: INVESTIGACIÓN OPERATIVA
Fin de INVESTIGACIÓN OPERATIVA alcanzado. Registros: 36
Éxito: 36 registros capturados.
[87/111] Procesando: INVESTIGACIÓN OPERATIVA - CHILCA
Fin de INVESTIGACIÓN OPERATIVA - CHILCA alcanzado. Registros: 27
Éxito: 27 registros capturados.
[88/111] Procesando: LENGUAS, TRADUCCIÓN E INTERPRETACIÓN
Fin de LENGUAS, TRADUCCIÓN E INTERPRETACIÓN alcanzado. Registros: 178
Éxito: 178 registros capturados.
[89/111] Procesando: LINGUÍSTICA
Fin de LINGUÍSTICA alcanzado. Registros: 62
Éxito: 62 registros capturados.
[90/111] Procesando: LITERATURA
Fin de LITERATURA alcanzado. Registros: 93
Éxito: 93 registros capturados.
[91/111] Procesando: MARKETING
Fin de MARKETING alcanzado. Registros: 162
Éxito: 162 registros capturados.
[92/111] Procesando: MATEMÁTICA
Fin de MATEMÁTICA alcanzado. Registros: 45
Éxito: 45 registros capturados.
[93/111] Procesando: MEDICINA HUMANA
Fin de MEDICINA HUMANA alcanzado. Registros: 4350
Éxito: 4350 registros capturados.
[94/111] Procesando: MEDICINA VETERINARIA
Fin de MEDICINA VETERINARIA alcanzado. Registros: 423
Éxito: 423 registros capturados.
[95/111] Procesando: MICROBIOLOGÍA Y PARASITOLOGÍA
Fin de MICROBIOLOGÍA Y PARASITOLOGÍA alcanzado. Registros: 92
Éxito: 92 registros capturados.
[96/111] Procesando: NUTRICION
Fin de NUTRICION alcanzado. Registros: 211
Éxito: 211 registros capturados.
[97/111] Procesando: OBSTETRICIA
Fin de OBSTETRICIA alcanzado. Registros: 411
Éxito: 411 registros capturados.
[98/111] Procesando: ODONTOLOGÍA
Fin de ODONTOLOGÍA alcanzado. Registros: 482
Éxito: 482 registros capturados.
[99/111] Procesando: PRESUPUESTO Y FINANZAS PÚBLICAS
Fin de PRESUPUESTO Y FINANZAS PÚBLICAS alcanzado. Registros: 77
Éxito: 77 registros capturados.
[100/111] Procesando: PRESUPUESTO Y FINANZAS PÚBLICAS - S.J.L
Fin de PRESUPUESTO Y FINANZAS PÚBLICAS - S.J.L alcanzado. Registros: 29
Éxito: 29 registros capturados.
[101/111] Procesando: PSICOLOGÍA
Fin de PSICOLOGÍA alcanzado. Registros: 1110
Éxito: 1110 registros capturados.
[102/111] Procesando: PSICOLOGÍA - CHILCA
Fin de PSICOLOGÍA - CHILCA alcanzado. Registros: 39
Éxito: 39 registros capturados.
[103/111] Procesando: PSICOLOGÍA ORGANIZACIONAL Y DE LA GESTIÓN HUMANA
Fin de PSICOLOGÍA ORGANIZACIONAL Y DE LA GESTIÓN HUMANA alcanzado. Registros: 215
Éxito: 215 registros capturados.
[104/111] Procesando: QUÍMICA
Fin de QUÍMICA alcanzado. Registros: 55
Éxito: 55 registros capturados.
[105/111] Procesando: SOCIOLOGÍA
Fin de SOCIOLOGÍA alcanzado. Registros: 132
Éxito: 132 registros capturados.
[106/111] Procesando: TEC. MED. LAB. CLÍNICO Y ANATOMÍA PATOLÓGICA
Fin de TEC. MED. LAB. CLÍNICO Y ANATOMÍA PATOLÓGICA alcanzado. Registros: 157
Éxito: 157 registros capturados.
[107/111] Procesando: TEC. MED. RADIOLOGÍA
Fin de TEC. MED. RADIOLOGÍA alcanzado. Registros: 148
Éxito: 148 registros capturados.
[108/111] Procesando: TEC. MED. TERAPIA FÍSICA Y REHABILITACIÓN
Fin de TEC. MED. TERAPIA FÍSICA Y REHABILITACIÓN alcanzado. Registros: 161
Éxito: 161 registros capturados.
[109/111] Procesando: TEC. MED. TERAPIA OCUPACIONAL
Fin de TEC. MED. TERAPIA OCUPACIONAL alcanzado. Registros: 144
Éxito: 144 registros capturados.
[110/111] Procesando: TOXICOLOGÍA
Fin de TOXICOLOGÍA alcanzado. Registros: 35
Éxito: 35 registros capturados.
[111/111] Procesando: TRABAJO SOCIAL
Fin de TRABAJO SOCIAL alcanzado. Registros: 174
Éxito: 174 registros capturados.
------------------------------
¡PROCESO COMPLETADO!
Total de registros consolidados: 25880
Archivo guardado en: output/resultados_sanmarcos.xlsx

---
## 📊 Step 6 — Data Analysis

Now that all the data is consolidated in `df_final`, we explore it to extract meaningful insights: which programs received the most applicants, how many candidates were admitted vs eliminated, and what the top scores look like across all programs.

In [13]:
import pandas as pd

# Cargamos el Excel ya generado para el análisis
df_final = pd.read_excel("output/resultados_sanmarcos.xlsx")

# Resumen general
total_postulantes = len(df_final)
total_carreras    = df_final["Carrera"].nunique()

print("📋 General Summary — UNMSM Admissions 2026-II")
print(f"  Total applicant records : {total_postulantes:,}")
print(f"  Total academic programs : {total_carreras}")
print(f"  Columns available       : {list(df_final.columns)}")
print()
print(df_final.head())

📋 General Summary — UNMSM Admissions 2026-II
  Total applicant records : 25,880
  Total academic programs : 111
  Columns available       : ['Carrera', 'Código', 'Apellidos y Nombres', 'Escuela', 'Puntaje', 'Mérito E.P.', 'Observación']

          Carrera  Código               Apellidos y Nombres         Escuela  \
0  ADMINISTRACIÓN  656550      ABAD SALGADO, SOFIA ESTRELLA  ADMINISTRACIÓN
1  ADMINISTRACIÓN  565808   ACUÑA ECHEBARRIA, YAMILA SORAYA  ADMINISTRACIÓN
2  ADMINISTRACIÓN  658780      ACUÑA PACOTAIPE, DULCE MARIA  ADMINISTRACIÓN
3  ADMINISTRACIÓN  651014  AGUERO VIDARTE, ADRIAN SEBASTIAN  ADMINISTRACIÓN
4  ADMINISTRACIÓN  658610       AGUIRRE RAMOS, JOGAN ALYAIR  ADMINISTRACIÓN

    Puntaje  Mérito E.P.                                       Observación
0   461.375          NaN                                               NaN
1  1074.875         41.0                                   ALCANZÓ VACANTE
2   797.375          NaN                                               NaN
3   826.125          NaN  Articulo N° 5 del Reglamento de Admisión 2026-II
4   780.125          NaN                                               NaN

### 🏆 Top 10 Most Competitive Programs

Which programs attracted the most applicants? High applicant counts usually indicate high demand and, consequently, tougher competition for available spots.

In [12]:
# Top 10 carreras por número de postulantes
top10_carreras = (
    df_final.groupby("Carrera")
    .size()
    .reset_index(name="total_postulantes")
    .sort_values("total_postulantes", ascending=False)
    .head(10)
    .reset_index(drop=True)
)

print("🏆 Top 10 Most Competitive Programs (by number of applicants):")
display(top10_carreras)

🏆 Top 10 Most Competitive Programs (by number of applicants):

                                      Carrera  total_postulantes
0                             MEDICINA HUMANA               4350
1                                     DERECHO               1873
2                                  PSICOLOGÍA               1110
3                      INGENIERÍA DE SISTEMAS                875
4                       INGENIERÍA INDUSTRIAL                866
5  ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES                805
6                                    ECONOMÍA                659
7                            INGENIERÍA CIVIL                642
8                                  ENFERMERÍA                602
9                              ADMINISTRACIÓN                553

### ✅ Admission Results — Who Got In?

The `Observación` column contains the admission status of each applicant. We analyze how many were admitted (`ingresante`) versus eliminated across all programs.

In [11]:
# Primero vemos los valores reales en la columna Observación
print("📋 Unique values in 'Observación' column:")
print(df_final["Observación"].value_counts().to_string())

# Filtramos ingresantes usando los valores exactos que aparecen
ingresantes = df_final[df_final["Observación"].str.upper().str.contains("INGRESANTE", na=False)]

obs_counts = (
    df_final["Observación"]
    .value_counts()
    .reset_index()
)
obs_counts.columns = ["observacion", "total"]
obs_counts["porcentaje"] = (obs_counts["total"] / len(df_final) * 100).round(2)

print("\n📊 Admission Results Distribution:")
display(obs_counts)

📋 Unique values in 'Observación' column:
Observación
ALCANZÓ VACANTE                                               4764
Articulo N° 5 del Reglamento de Admisión 2026-II               323
AUSENTE                                                        247
AUSENTE - Articulo N° 5 del Reglamento de Admisión 2026-II       3

📊 Admission Results Distribution:

                                         observacion  total  porcentaje
0                                    ALCANZÓ VACANTE   4764       18.41
1   Articulo N° 5 del Reglamento de Admisión 2026-II    323        1.25
2                                            AUSENTE    247        0.95
3  AUSENTE - Articulo N° 5 del Reglamento de Admi...      3        0.01

### 🥇 Top Scorers Across All Programs

Who achieved the highest admission scores in the entire exam? We convert the `Puntaje` column to numeric and rank applicants across all programs.

In [9]:
# Convertimos Puntaje a numérico (algunos valores pueden ser strings)
df_final["Puntaje"] = pd.to_numeric(df_final["Puntaje"], errors="coerce")

# Top 10 puntajes más altos
top_scores = (
    df_final[["Apellidos y Nombres", "Carrera", "Puntaje", "Observación"]]
    .dropna(subset=["Puntaje"])
    .sort_values("Puntaje", ascending=False)
    .head(10)
    .reset_index(drop=True)
)

print("🥇 Top 10 Highest Scores Across All Programs:")
display(top_scores)

🥇 Top 10 Highest Scores Across All Programs:

,Apellidos y Nombres,Carrera,Puntaje,Observación
0,"VILCA CAQUI, ANGEL HANS",INGENIERÍA BIOMÉDICA,1717.375,ALCANZÓ VACANTE
1,"ESPINOZA ROJAS, GINO DANIEL",DERECHO,1638.000,ALCANZÓ VACANTE
2,"MAURICIO SOLORZANO, CRISTHIAN PIERO",MEDICINA HUMANA,1624.875,ALCANZÓ VACANTE
3,"SANCHEZ AZAÑA, JHANPIER ANGEL",MEDICINA HUMANA,1620.875,ALCANZÓ VACANTE
4,"BRUNO ANCHAISE, GIOVANNI PAOLO",INGENIERÍA INDUSTRIAL,1613.375,ALCANZÓ VACANTE
5,"FLORES JUNCO, GABRIEL ALONSO",MEDICINA HUMANA,1565.500,ALCANZÓ VACANTE
6,"LAZO TOVAR, MAXIMO VALENTINO",ARQUITECTURA Y URBANISMO,1565.500,ALCANZÓ VACANTE
7,"CASTRO SUCLUPE, KEVIN DAVID",INGENIERÍA DE SISTEMAS,1557.500,ALCANZÓ VACANTE
8,"HEREDIA MENDOZA, ALEXANDER PAOLO VICTOR",ECONOMÍA,1545.500,ALCANZÓ VACANTE
9,"FLORES ALARCON, JORGE ALEJANDRO",MATEMÁTICA,1537.500,ALCANZÓ VACANTE

### 📉 Least Demanded Programs

On the other end, which programs had the fewest applicants? This can reflect niche careers, less public awareness, or very specific admission profiles.

In [8]:
# Bottom 10 carreras por número de postulantes
bottom10_carreras = (
    df_final.groupby("Carrera")
    .size()
    .reset_index(name="total_postulantes")
    .sort_values("total_postulantes", ascending=True)
    .head(10)
    .reset_index(drop=True)
)

print("📉 Top 10 Least Demanded Programs (by number of applicants):")
display(bottom10_carreras)

📉 Top 10 Least Demanded Programs (by number of applicants):

                                         Carrera  total_postulantes
0                                          DANZA                  6
1                  INGENIERÍA ELÉCTRICA - CHILCA                 18
2                      CONTABILIDAD - VILLA RICA                 19
3                          CONTABILIDAD - HUARAL                 20
4                        EDUCACIÓN FÍSICA - OYÓN                 20
5  ADMINISTRACION MARITIMA Y PORTUARIA - CHANCAY                 21
6                            CONTABILIDAD - OYÓN                 21
7                    INGENIERÍA GEOLÓGICA - OYÓN                 23
8              ADMINISTRACIÓN DE TURISMO - S.J.L                 25
9               INVESTIGACIÓN OPERATIVA - CHILCA                 27

### 🎯 Average Score per Program (Top 15)

Which programs have the highest average admission scores? A high average suggests that the admitted pool was very competitive — the cutoff bar was raised by the strength of the applicant field.

In [7]:
# Promedio de puntaje por carrera — solo carreras con al menos 50 postulantes
# (evitamos distorsiones por muestras pequeñas como Danza o carreras de sede)
avg_score_by_carrera = (
    df_final.groupby("Carrera")
    .agg(total_postulantes=("Puntaje", "count"), avg_puntaje=("Puntaje", "mean"))
    .reset_index()
    .query("total_postulantes >= 50")  # mínimo 50 registros para que el promedio sea representativo
    .sort_values("avg_puntaje", ascending=False)
    .head(15)
    .reset_index(drop=True)
)
avg_score_by_carrera["avg_puntaje"] = avg_score_by_carrera["avg_puntaje"].round(3)

print("🎯 Top 15 Programs by Average Admission Score (min. 50 applicants):")
display(avg_score_by_carrera)

🎯 Top 15 Programs by Average Admission Score (min. 50 applicants):

                             Carrera  total_postulantes  avg_puntaje
0          CIENCIA DE LA COMPUTACIÓN                134      973.630
1               INGENIERÍA BIOMÉDICA                239      966.876
2   INGENIERÍA DE TELECOMUNICACIONES                125      946.820
3                   EDUCACIÓN FÍSICA                160      928.912
4                           HISTORIA                 80      918.797
5             INGENIERÍA ELECTRÓNICA                255      909.634
6             INGENIERÍA MECATRONICA                291      902.711
7                        LINGUÍSTICA                 62      901.298
8                 INGENIERÍA QUÍMICA                173      899.626
9                   INGENIERÍA CIVIL                642      898.677
10              INGENIERÍA ELÉCTRICA                172      895.387
11                  CIENCIA POLÍTICA                372      893.901
12            INGENIERÍA DE SOFTWARE                411      892.083
13          GENÉTICA Y BIOTECNOLOGÍA                170      891.941
14                          ECONOMÍA                659      890.121

## 🚀 Step 5 — Run the Full Scraping Loop

We iterate over all 111 programs, call the scraping function for each one, and consolidate every record into a single DataFrame. If a program fails for any reason, the `try/except` block logs the error and continues to the next one — so a single broken page does not stop the entire process.

At the end, the consolidated DataFrame is exported to `output/resultados_sanmarcos.xlsx`.

> **Final result:** 25,880 applicant records across 111 programs.